### ISSUE TITLE
Web European Conference

### ISSUE THREAD

**Issue by simonech** [TorinoJS/discussion#10]
Ciao,
a fine settembre, per la precisione sabato 26 settembre, si terrá a Milano, presso l'Univesitá Bicocca, la seconda edizione della Web European Conference.

Gli argomenti spazieranno da server side su .NET, NodeJS, Ruby ai Framework JS client-side, ad Azure e IoT.

Abbiamo giá alcuni speaker d'eccezione, come Scott Hanselman, per la prima volta ad un evento in Italia, a Dino Esposito, Massimiliano Mantione, Alessio Delmonti con IonicFramework, Sandro Paganotti e molti altre proposte ancora da valutare (https://github.com/Web-European-Conference/c4p/blob/master/proposal.json)

Maggiori informazioni: http://webnextconf.eu/
Le registrazioni sono giá aperte: https://webnextconf.eventbrite.com

Vi sarei grato se poteste annunciarlo ai membri del vosto user group e magari pubblicarlo tra i prossimi vostri eventi.

Grazie
Simone

**Comment by grigio** [comment]
Grazie per la segnalazione
