### ISSUE TITLE
TorinoJS #jsNight 1ott2015 - C4P

### ISSUE THREAD

**Issue by grigio** [TorinoJS/discussion#11]
Siamo quasi pronti per una nuova #jsNight per parlare di javascript e si terrà il 1 ottobre presso I3P del Politecnico di Torino.

Se siete interessati a partecipare attivamente c’é ancora uno slot libero per un relatore, inoltre per chi vuole, sarà possibile acquistare le [magliette di #TorinoJS](https://twitter.com/torinojs/status/606473778067931136) al costo di produzione di 10€ (fino ad esaurimento scorte).

[Info e registrazioni](http://www.eventbrite.com/e/biglietti-torinojs-jsnight-1ott2015-incontro-su-javascript-e-tecnologie-web-open-source-17551169019?aff=gh)

**Comment by terrinoni** [comment]
Questa volta spero di non riuscire a perdermelo...
La maglietta bisogna prenotarla prima o e possibile acquistarla direttamente all'evento?
Grazie.

**Comment by grigio** [comment]
Le magliette sono state prenotate dando l'acconto e specificando la taglia,.. tuttavia ce ne qualcuna in più.

**Comment by emiliano183** [comment]
Salve, ho appena fatto un talk su EcmaScript 2015 all'evento Mobile Tea 8 a Roma. Qui diapositive e codice.
https://github.com/josieusa/todo-vanilla-es2015
E se quello slot è ancora libero, sono interessato a tenere una sessione di 25 minuti, di cui, se volete, 10 minuti sullo stesso tema (cambiando il font...), e 15 minuti su una libreria che ha appena raggiunto la release 1.0 con fondi della community e che è un'evoluzione delle idee di Flux ed Elm. Anche perché sto cercando lavoro a Torino, e per questo voglio farmi conoscere.

**Comment by josieusa** [comment]
Salve, ho appena fatto un talk su EcmaScript 2015 all'evento Mobile Tea 8 a Roma. Qui diapositive e codice.
https://github.com/josieusa/todo-vanilla-es2015
E se quello slot è ancora libero, sono interessato a tenere una sessione di 25 minuti, di cui, se volete, 10 minuti sullo stesso tema (cambiando il font...), e 15 minuti su una libreria che ha appena raggiunto la release 1.0 con fondi della community e che è un'evoluzione delle idee di Flux ed Elm. Anche perché sto cercando lavoro a Torino, e per questo voglio farmi conoscere.

**Comment by grigio** [comment]
Ciao e benvenuto @josieusa , va bene. Mandami appena puoi il titolo e qualche settimana prima ti chiederò la conferma

**Comment by josieusa** [comment]
Ecco il titolo:
Part 1: The future of Angular and React: Vanilla JS
Part 2: The future of Flux and Angular's MVW: Vanilla MV*

**Comment by grigio** [comment]
@josieusa te l'ho accorciato un po'.
E anche questa puntata é a posto, online il programma provvisorio

**Comment by grigio** [comment]
@josieusa allora mi confermi che giovedì sarai relatore?

Luigi

**Comment by josieusa** [comment]
Confermo, anche se dato che verrò da Roma col treno potrebbe essere meglio che il mio talk sia per ultimo.

**Comment by grigio** [comment]
Ok, grazie per aver avvisato

**Comment by cluspac** [comment]
Ciao @josieusa la presentazione che avevi fatto a TorinoJS del primo Ottobre era interessante ed ho apprezzato le battute in piemontese. Potresti pubblicarla?

Grazie
