### ISSUE TITLE
Magliette di TorinoJS?

### ISSUE THREAD

**Issue by grigio** [TorinoJS/discussion#2]
@antonellopasella ha proposto di fare delle magliette per TorinoJS. I loghi in SVG sono nel repository.

**TODO**
- scegliere la variante da stampare
- valutare se è il caso di realizzare le magliette per il 6 maggio o all'appuntamento dopo
  - raccogliere gli ordini di taglia e quantità

**Comment by antonellopasella** [comment]
Possiamo pensare di farne un tot per "lo staff" e poi a richiesta magari mettere su eventbrite la prenotazione (con pagamento anticipato).

10gg di anticipo per la stampa senza stress. se serve serigrafia (almeno una ventina) forse qualcosina in più,

**Comment by grigio** [comment]
@physiocoder @puria @alearcy

**Comment by alearcy** [comment]
Good! Sapete già eventualmente dove fare la stampa?

**Comment by physiocoder** [comment]
C'è già un preventivo ed una grafica?

Inviato da iPhone

**Comment by antonellopasella** [comment]
Io pensavo logo e TorinoJS.

Solitamente 12/15€ con stampa digitale (non serigrafia che in questo caso
andrebbe benissimo) me la cavo
Il giorno lun 23 mar 2015 alle 12:06 Roberto Ferro notifications@github.com
ha scritto:

**Comment by grigio** [comment]
@madbob Per le magliette del LinuxDay su che prezzi eri?

**Comment by madbob** [comment]
115 magliette solo fronte, taglie varie: 4.50 euri cad. + 15 euri di impianto + 22% IVA. Totale: 5.65 euri a maglietta. Da ExtraLiberi: http://www.extraliberi.it/
Facendo li' le magliette da diversi anni ogni volta ci applica un po' di sconto, dunque magari da listino (e con quantita' piu' piccole) ti chiede un po' di piu', ma a Torino te la vedo difficile trovar tanto di meglio.

**Comment by grigio** [comment]
@madbob tnx, anche quelle staff avevano quel prezzo?

@all oppure vediamo come va il primo incontro e poi facciamo l'ordine più grande

**Comment by madbob** [comment]
Quelle per lo staff, fronte/retro, a 5 euri (+ impianto, + IVA).

**Comment by grigio** [comment]
Che ne dite?
![screenshot from 2015-03-24 14 02 25](https://cloud.githubusercontent.com/assets/8074/6802201/b08d89a6-d22e-11e4-9553-8b8db6b8d531.png)

**Comment by antonellopasella** [comment]
Beh, 5€ #sticazzi
Il giorno mar 24 mar 2015 alle 14:08 Luigi Maselli notifications@github.com
ha scritto:

**Comment by grigio** [comment]
@madbob come fa ad avere quei prezzi? :) Mi sembrano doppi

**Comment by alearcy** [comment]
Mi piace la preview @grigio

**Comment by antonellopasella** [comment]
Io metterei anche torino (in piccolo sopra js)

**Comment by antonellopasella** [comment]
@beinnova

**Comment by beinnova** [comment]
@antonellopasella  grazie per l'invito!

**Comment by madbob** [comment]
@grigio stampa serigrafica ad un solo colore, grosse quantità (lo scorso anno tra le magliette solo fronte per il pubblico e quelle fronte/retro per lo staff ne abbiam prese 150) e fedeltà del cliente ;-)
Scrivigli chiedendo un preventivo, specifica che sei uno del LinuxDayTorino (che magari ci scappa lo sconto), e fatti due conti.

**Comment by alearcy** [comment]
@antonellopasella io la preferisco così minimal, Torino lo si capisce dalla mole

**Comment by grigio** [comment]
@antonellopasella con la scritta sopra verrebbe così, ma anche a me piace un po' più senza che è più minimale

_variante b_
![screenshot from 2015-03-24 16 23 05](https://cloud.githubusercontent.com/assets/8074/6805237/35d313c0-d242-11e4-89f8-f09b192ab512.png)

**Comment by antonellopasella** [comment]
Concordo, via la scritta 😄

Il martedì 24 marzo 2015, Luigi Maselli notifications@github.com ha
scritto:

> @antonellopasella https://github.com/antonellopasella con la scritta
> sopra verrebbe così, ma anche a me piace più senza che è più minimale
> 
> [image: screenshot from 2015-03-24 15 53 48]
> https://cloud.githubusercontent.com/assets/8074/6804488/40b4d3ea-d23e-11e4-82f4-b97bfea9c88a.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TorinoJS/discussion/issues/2#issuecomment-85540351.

## 

Antonello Pasella http://www.pasella.it

**Comment by grigio** [comment]
Allora rimane da decidere:
- se farle per il 6 maggio o aspettare per poi fare un ordine più grande

Io non ho una forte opinione in merito, la maglietta mi sembra carina, ma preferirei che l'ordine fosse sufficientemente grande da stare sotto i 10€ cad.

**Comment by alearcy** [comment]
Dipende a chi andranno le magliette oltre allo staff. Se vogliamo fare una cosa tipo quella fatta al Meteor Day sotto forma di gioco, ne facciamo 5 in più giusto per i vincitori e basta, perciò non ci sarà più bisogno di fare un ordine grande e le prendiamo tutte per quel giorno. Se invece diventa prioritario l'aspetto economico per stare sotto i 10€, nessuno ci vieta lo stesso di acquistarne un quantitativo maggiore per quel giorno e decidere successivamente cosa fare delle magliette in più.

**Comment by antonellopasella** [comment]
Io qualche soldo in più lo metto volentieri.
Male che vada le regaliamo agli amici :D

Sicuramente quella "staff" la voglio :D

**Comment by grigio** [comment]
Mi auguro che tra il pubblico del 6maggio ci saranno i relatori delle puntate future, quindi non dividerei in staff e non staff.

Tenere il prezzo basso significa anche una maggiore diffusione delle magliette e quindi dell'iniziativa TorinoJS

Ps: Non abbiamo parlato di cos'é TorinoJS, ma secondo me un evento come quello del 6 può essere replicato ogni volta che si racimolano almeno 3 relatori e c'é un luogo adeguato che ci ospiti

**Comment by alearcy** [comment]
Se è un'iniziativa lancio sono d'accordo @grigio

**Comment by joviberton** [comment]
jovi +1

**Comment by foysalit** [comment]
:+1:  Looks cool. love the logo. count me in. Ci vediamo domani sera :)

**Comment by grigio** [comment]
Prenotate 10 in prevendita. Tiratura 30. Disponibili dalla prossima #jsNight

**Comment by grigio** [comment]
Arrivate! Tiratura limitata, priorità a prevendite e relatori :P
![20150604_163733](https://cloud.githubusercontent.com/assets/8074/7987024/3f211d1a-0adb-11e5-9ba9-5021eac0f5df.JPG)

**Comment by antonellopasella** [comment]
Io io io io io
Il giorno gio 4 giu 2015 alle 16:46 Luigi Maselli notifications@github.com
ha scritto:

**Comment by beinnova** [comment]
Bellissime!

P.S. Antonello mettiti in coda :smile: 

## 

_Be__innova_ di _Giorgio Cerruti_
_WebSites | IT consultant | Web Developer_
_Phone: +39 340/87.68.326 :: Skype: beinnova_
_P.IVA: 10755560017_
_Visit Beinnova http://www.beinnova.it Site_
- Giorgio Cerruti
  http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/

**Comment by grigio** [comment]
Datemi il tempo di fare il tweet! :D Sì obbiettivamente sono molto carine

**Comment by psicomante** [comment]
Belleeeee! Quindi i relatori la avranno? :santa:

**Comment by antonellopasella** [comment]
Si, ma dovranno comunque pagare... :D

2015-06-04 17:56 GMT+02:00 Roberto Pesando notifications@github.com:

> Belleeeee! Quindi i relatori la avranno? [image: :santa:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TorinoJS/discussion/issues/2#issuecomment-108945608.

## 

Antonello Pasella http://www.pasella.it

**Comment by psicomante** [comment]
sono tempi di magra :D

**Comment by alearcy** [comment]
dajeeeee belle! io voglio quella gialla!! :-D

**Comment by grigio** [comment]
quando avremo gli sponsor di MilanoJS saranno gratis :p Comunque la cifra é bassa ed é al costo di produzione 10€

**Comment by psicomante** [comment]
chiaramente sto scherzando :D sono felicissimo di poterle comprare (per la cronaca sono stato uno degli organizzatori dei DrupalCamp e so cosa significa organizzare un evento :D)
