### ISSUE TITLE
website

### ISSUE THREAD

**Issue by vesparny** [TorinoJS/discussion#3]
Ciao ragazzi, 
complimenti per l'iniziativa.

Erano anni che dicevo che sarebbe stato bello organizzare un gruppo a Torino, ma alla fine non mi sono mai deciso a fare qualcosa attivamente.

Avete già un sito?

Se vi va posso darvi una mano, anche se sto poco a torino ultimamente, col cuore sono sempre la :)

**Comment by grigio** [comment]
Anch'io e poi alla fine mi sono deciso :) Vediamo come evolve.

Il sito per ora non è una priorità, nel senso che:
- chi vuole partecipare ha https://github.com/TorinoJS/discussion
- chi vuole solo seguire esternamente ha https://twitter.com/torinojs
- chi è interessato al singolo evento o programma ha http://www.eventbrite.it/e/biglietti-jsnight-torino-incontro-su-javascript-e-tecnologie-web-open-source-16247263001

Ad ogni modo se il progetto suscita interesse potrei mettere una landing page tipo https://github.com/meteor-italia/meteor-italia.github.io e renderla modificabile ai membri.

Tu che sito avevi in mente e per fare cosa?

**Comment by vesparny** [comment]
@grigio pensavo giusto ad una landing, tipo quella di milanoJS.
In ogni caso concordo son te sul fatto che non è una priorità.

Per le discussioni credi github vada bene o meglio una mailing list?

**Comment by grigio** [comment]
@vesparny La mia personale idea su _TorinoJS_, non è quella di creare l'ennesima sovrastruttura, ma di utilizzare quello che c'é già per coordinarsi e fare qualcosa con chi c'é.

Riguardo la mailinglist, quelle che seguivo su Torino sono tutte moribonde o usate per comunicazioni OT, quindi molto meglio Github che: ha il wiki, la possibilità di creare discussioni che possono essere seguite oppure no, fa hosting di pagine statiche e praticamente tutti quelli che hanno a che fare con javascript e open source già usano

**Comment by vesparny** [comment]
:+1:

**Comment by grigio** [comment]
Tengo aperto perché può interessare anche ad altri

**Comment by grigio** [comment]
adesso una paginetta c'é http://torinojs.github.io/
