### ISSUE TITLE
streaming jsNight

### ISSUE THREAD

**Issue by vesparny** [TorinoJS/discussion#7]
Ciao a tutti,

sarebbe carino se poteste mandare in streaming la prima serata, per dare la possibilità a chi come me non potrà essere presente.

anche un semplice computer puntato sullo speaker, nulla di complicato.

che ne dite?

**Comment by grigio** [comment]
L'ideale sarebbe una camera e un cavalletto, cmq se qualcuno vuole prendersi l'incarico faccia pure.
Le slide e il codice mostrato, cmq sarà messo da qualche parte online

**Comment by vesparny** [comment]
ok, anche un semplice hangout andrebbe bene, rapido e indolore.

**Comment by ghost** [comment]
ciao a tutti, ci sono novità in merito a quanto chiesto da vesparny?

**Comment by terrinoni** [comment]
Purtroppo non riesco ad essere presente nemmeno io; sarebbe grandioso avere uno streaming.
Ci sono novita' a riguardo?

**Comment by grigio** [comment]
Il fine principale dell'evento è anche quello di incontrarsi di persona. Ho provato a chiedere, ma non si è fatto avanti nessuno quindi per adesso chiudo.
