### ISSUE TITLE
Proposta di modifica scaletta

### ISSUE THREAD

**Issue by alearcy** [TorinoJS/discussion#8]
Ciao ragazzi, volevo proporre una piccola modifica alla scaletta. L'argomento che tratto parla dei tools e delle metodologie per migliorare il workflow lavorativo. E' uno speech particolarmente adatto a chi si affaccia per la prima volta al web development o per i veterani che ancora non usano alcune tecnologie. Alcune di queste, come Gulp, saranno sicuramente menzionate nei vostri speech. A rigor di logica penso sia meglio che un intervento "leggero" come il mio sia adatto in apertura in modo tale da spianare la strada a certi argomenti e terminologie che poi verranno successivamente utilizzate.
Ditemi che ne pensate ;-)
ciao

**Comment by grigio** [comment]
Ciao @alearcy , in realtà l'ordine dei talk corrisponde solo all'ordine con il quale mi hanno risposto i relatori e i talk alla fine sono tutti abbastanza indipendenti. Tendenzialmente la terrei così, visto che l'hanno già copia-incollata diversi siti.
