### ISSUE TITLE
Consigio

### ISSUE THREAD

**Issue by beinnova** [TorinoJS/discussion#9]
Posso consigliare di modificare il nome da Torino JS a Torino.js.

**Comment by grigio** [comment]
Quello che proponi potrebbe confondersi con un nome di dominio. Comunque "TorinoJS" o "Torino JS" è il pattern utilizzato dai vari gruppi javascript sparsi per il mondo (ed è anche pratico come #hashtag )

![schermata 2015-05-07 alle 09 50 48](https://cloud.githubusercontent.com/assets/8074/7510631/a01cf254-f49e-11e4-85ce-4b8617fcf6d8.png)

**Comment by beinnova** [comment]
Ricevuto.

Il giorno 7 maggio 2015 09:56, Luigi Maselli notifications@github.com ha
scritto:

> Quello che proponi potrebbe confondersi con un nome di dominio. Comunque
> "TorinoJS" o "Torino JS" è il pattern utilizzato dai vari gruppi javascript
> sparsi per il mondo (ed è anche pratico come #hashtag )
> 
> [image: schermata 2015-05-07 alle 09 50 48]
> https://cloud.githubusercontent.com/assets/8074/7510631/a01cf254-f49e-11e4-85ce-4b8617fcf6d8.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TorinoJS/discussion/issues/9#issuecomment-99760001.

## 

_Be__innova_ di _Giorgio Cerruti_
_WebSites | IT consultant | Web Developer_
_Phone: +39 340/87.68.326 :: Skype: beinnova_
_P.IVA: 10755560017_
_Visit Beinnova http://www.beinnova.it Site_
- Giorgio Cerruti
  http://it.linkedin.com/pub/giorgio-cerruti/31/422/852/
